### PR TITLE
dont like it just get rid of it

### PR DESCRIPTION
**Pull request by dreamhopping**
idnt lkike this

### CODE REVIEW

**Review by deamsy — APPROVED** [review]

**Comment by deamsy** [comment]
great addition

**Review by GamingGeek — APPROVED** [review]

**Comment by GamingGeek** [comment]
yes

**Review by asbyth — APPROVED** [review]

**Comment by asbyth** [comment]
among us

**Review by proudmuslim-dev — APPROVED** [review]

**Comment by proudmuslim-dev** [comment]
Amazing

**Review by crang-real — APPROVED** [review]

**Comment by crang-real** [comment]
this is the best thing ever made

**Review by TymanWasTaken — APPROVED** [review]
no

**Comment by MyerFire** [comment]
this would make it so much better!!!!!!!

**Comment by SirNapkin1334** [comment]
get real

**Comment by proudmuslim-dev** [comment]
Cringe

**Comment by SirNapkin1334** [comment]
Cringe

**Comment by proudmuslim-dev** [comment]
You're cringe

**Comment by deamsy** [comment]
ባደረካቸው ድርጊቶች ምክንያት ቤተሰቦችዎ ደሙን ያፈሳሉ ፡፡ ለድርጊቶችዎ የዘላለም ሥቃይ ይሰማቸዋል ፡፡ ያፈሰሱ እንባዎች ወደ ደም ይለወጣሉ ፣ የሚሰማቸው ህመም ሊቋቋሙት የማይችሉት ይሆናሉ ፡፡ በቅርቡ ለብቻዎ ትሆናላችሁ

**Comment by proudmuslim-dev** [comment]
ባደረካቸው ድርጊቶች ምክንያት ቤተሰቦችዎ ደሙን ያፈሳሉ ፡፡ ለድርጊቶችዎ የዘላለም ሥቃይ ይሰማቸዋል ፡፡ ያፈሰሱ እንባዎች ወደ ደም ይለወጣሉ ፣ የሚሰማቸው ህመም ሊቋቋሙት የማይችሉት ይሆናሉ ፡፡ በቅርቡ ለብቻዎ ትሆናላችሁ

**Comment by SirNapkin1334** [comment]
ok pog-generaller

**Comment by deamsy** [comment]
ok racist

**Comment by proudmuslim-dev** [comment]
racism smh

**Comment by SirNapkin1334** [comment]
⠀⠀⠀⡯⡯⡾⠝⠘⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢊⠘⡮⣣⠪⠢⡑⡌
⠀⠀⠀⠟⠝⠈⠀⠀⠀⠡⠀⠠⢈⠠⢐⢠⢂⢔⣐⢄⡂⢔⠀⡁⢉⠸⢨⢑⠕⡌
⠀⠀⡀⠁⠀⠀⠀⡀⢂⠡⠈⡔⣕⢮⣳⢯⣿⣻⣟⣯⣯⢷⣫⣆⡂⠀⠀⢐⠑⡌
⢀⠠⠐⠈⠀⢀⢂⠢⡂⠕⡁⣝⢮⣳⢽⡽⣾⣻⣿⣯⡯⣟⣞⢾⢜⢆⠀⡀⠀⠪
⣬⠂⠀⠀⢀⢂⢪⠨⢂⠥⣺⡪⣗⢗⣽⢽⡯⣿⣽⣷⢿⡽⡾⡽⣝⢎⠀⠀⠀⢡
⣿⠀⠀⠀⢂⠢⢂⢥⢱⡹⣪⢞⡵⣻⡪⡯⡯⣟⡾⣿⣻⡽⣯⡻⣪⠧⠑⠀⠁⢐
⣿⠀⠀⠀⠢⢑⠠⠑⠕⡝⡎⡗⡝⡎⣞⢽⡹⣕⢯⢻⠹⡹⢚⠝⡷⡽⡨⠀⠀⢔
⣿⡯⠀⢈⠈⢄⠂⠂⠐⠀⠌⠠⢑⠱⡱⡱⡑⢔⠁⠀⡀⠐⠐⠐⡡⡹⣪⠀⠀⢘
⣿⣽⠀⡀⡊⠀⠐⠨⠈⡁⠂⢈⠠⡱⡽⣷⡑⠁⠠⠑⠀⢉⢇⣤⢘⣪⢽⠀⢌⢎
⣿⢾⠀⢌⠌⠀⡁⠢⠂⠐⡀⠀⢀⢳⢽⣽⡺⣨⢄⣑⢉⢃⢭⡲⣕⡭⣹⠠⢐⢗
⣿⡗⠀⠢⠡⡱⡸⣔⢵⢱⢸⠈⠀⡪⣳⣳⢹⢜⡵⣱⢱⡱⣳⡹⣵⣻⢔⢅⢬⡷
⣷⡇⡂⠡⡑⢕⢕⠕⡑⠡⢂⢊⢐⢕⡝⡮⡧⡳⣝⢴⡐⣁⠃⡫⡒⣕⢏⡮⣷⡟
⣷⣻⣅⠑⢌⠢⠁⢐⠠⠑⡐⠐⠌⡪⠮⡫⠪⡪⡪⣺⢸⠰⠡⠠⠐⢱⠨⡪⡪⡰
⣯⢷⣟⣇⡂⡂⡌⡀⠀⠁⡂⠅⠂⠀⡑⡄⢇⠇⢝⡨⡠⡁⢐⠠⢀⢪⡐⡜⡪⡊
⣿⢽⡾⢹⡄⠕⡅⢇⠂⠑⣴⡬⣬⣬⣆⢮⣦⣷⣵⣷⡗⢃⢮⠱⡸⢰⢱⢸⢨⢌
⣯⢯⣟⠸⣳⡅⠜⠔⡌⡐⠈⠻⠟⣿⢿⣿⣿⠿⡻⣃⠢⣱⡳⡱⡩⢢⠣⡃⠢⠁
⡯⣟⣞⡇⡿⣽⡪⡘⡰⠨⢐⢀⠢⢢⢄⢤⣰⠼⡾⢕⢕⡵⣝⠎⢌⢪⠪⡘⡌⠀
⡯⣳⠯⠚⢊⠡⡂⢂⠨⠊⠔⡑⠬⡸⣘⢬⢪⣪⡺⡼⣕⢯⢞⢕⢝⠎⢻⢼⣀⠀
⠁⡂⠔⡁⡢⠣⢀⠢⠀⠅⠱⡐⡱⡘⡔⡕⡕⣲⡹⣎⡮⡏⡑⢜⢼⡱⢩⣗⣯⣟
⢀⢂⢑⠀⡂⡃⠅⠊⢄⢑⠠⠑⢕⢕⢝⢮⢺⢕⢟⢮⢊⢢⢱⢄⠃⣇⣞⢞⣞⢾
⢀⠢⡑⡀⢂⢊⠠⠁⡂⡐⠀⠅⡈⠪⠪⠪⠣⠫⠑⡁⢔⠕⣜⣜⢦⡰⡎⡯⡾⡽

**Pull request closed without merging**
